extends Node

enum Style {BASIC, COWBOY, ENGLISH, BASEBALL, BEANIE, STRAW}
enum State {DEFAULT, FISHING, BUILDING, SHOP, COOKING}
enum Tool {AXE, HOE, SWORD, WATER, FISH, SEED}
enum Machine {SPRINKLER, FISHER, SCARECROW, DELETE}
enum Seed {TOMATO, CORN, PUMPKIN, WHEAT, PANDAN}
enum Item {WOOD, APPLE, TOMATO, CORN, WHEAT, PUMPKIN, FISH, FISH_STEW, CORNBREAD, TOMATO_SOUP, PUMPKIN_PIE, BAKED_APPLE, PANDAN, RICE_FLOUR, PALM_SUGAR, COCONUT_MILK, DODOL, GINGER, CHILI, SCALLION, PALAPA}
enum Shop {MAIN, HAT, COOKING}
